export {
  angularInspectorRequiredDevModeGlobalNames,
  angularInspectorRuntimeAdapterTargets,
  createAngularDevModeGlobalsInspectorAdapter,
  createAngularInspectorAdapter,
  defaultAngularInspectorAdapterCapabilities,
  defaultAngularInspectorRuntimeConfig,
  hasRequiredAngularDevModeGlobals,
  resolveAngularDevModeGlobals,
  resolveAngularInspectorRuntimeConfig,
  type AngularDevModeGlobalsApi,
  type AngularInspectorAdapterCapabilities,
  type AngularInspectorAdapterContract,
  type AngularInspectorRuntimeAdapterTarget,
  type AngularInspectorRuntimeConfig,
  type ResolvedAngularInspectorRuntimeConfig,
} from './adapters/base';
export {
  destroyInspectorBridge,
  initInspectorBridge,
  type InitInspectorBridgeOptions,
  type InspectorBridgeRequestHandlers,
} from './bridgeRuntime';
export {
  bootstrapEmbeddedInspectorBridge,
  initDevEmbeddedInspectorBridge,
  type BootstrapEmbeddedInspectorBridgeOptions,
  type InitDevEmbeddedInspectorBridgeOptions,
} from './embeddedBootstrap';
export {
  ITERATION_INSPECTOR_CHANNEL,
  bootIterationInspectorRuntime,
  buildIterationElementSelection,
  createIterationInspectorRuntime,
  isIterationInspectorParentMessage,
  isIterationInspectorRuntimeMessage,
  type IterationElementBounds,
  type IterationEditableValueFieldId,
  type IterationEditableValues,
  type IterationElementLocator,
  type IterationElementSelection,
  type IterationInspectorDebugDetails,
  type IterationInspectorInvalidationReason,
  type IterationInspectorParentMessage,
  type IterationInspectorRuntime,
  type IterationInspectorRuntimeCapability,
  type IterationInspectorRuntimeMessage,
  type IterationInspectorSelectionMode,
  type IterationPreviewEditError,
  type IterationPreviewEditErrorCode,
  type IterationPreviewEditOperation,
  type IterationPreviewEditValueType,
  type IterationPreviewTargetEdit,
  type IterationScrollOffset,
} from './iterationInspector';
